#!/bin/bash

# Gather System Information
sys_hostname=$(hostname)
sys_os=$(lsb_release -d | awk -F"\t" '{print $2}')
sys_uptime=$(uptime -p)

# Gather Hardware Information
hw_cpu_model=$(cat /proc/cpuinfo | grep "model name" | uniq | awk -F": " '{print $2}')
hw_cpu_speed=$(lscpu | grep "MHz" | awk '{print $3}')
hw_ram=$(free -h | awk '/Mem/ {print $2}')
hw_disk_usage=$(df -h | awk '$NF=="/"{printf "Disk: %d/%dGB (%s)\n", $3,$2,$5}')
hw_video_card=$(lspci | grep -i "VGA" | awk -F": " '{print $2}')

# Gather Network Information
net_fqdn=$(hostname -f)
net_host_address=$(hostname -I | awk '{print $1}')
net_gateway=$(ip route | awk '/default/ {print $3}')
net_dns=$(cat /etc/resolv.conf | grep "nameserver" | awk '{print $2}')
net_interfaces=$(ip -o link show | awk -F': ' '{print $2}')
net_make_model=$(lspci | grep -i "network" | awk -F": " '{print $2}')
net_ip_cidr=$(ip -o -4 addr show $net_interface | awk '/inet / {print $4}')

# Gather System Status
sys_users=$(who | awk '{print $1}' | sort | uniq | tr '\n' ',' | sed 's/,$//')
sys_disk_space=$(df -h | awk '/^\/dev/ {print $6" "$4}')
sys_process_count=$(ps aux | wc -l)
sys_load_averages=$(uptime | awk -F'average: ' '{ print $2 }')
sys_memory_allocation=$(free -m)
listening_ports=$(ss -tuln | awk '{print $5}' | cut -d ':' -f2 | grep -E "^[0-9]" | sort -n | uniq | tr '\n' ', ' | sed 's/,$//')
ufw_rules=$(sudo ufw status numbered | awk '{print $1" "$2" "$3}')

# Generate Report
echo ""
echo "System Report generated by $(whoami), $(date)"
echo ""
echo "System Information"
echo "------------------"
echo "Hostname: $sys_hostname"
echo "OS: $sys_os"
echo "Uptime: $sys_uptime"
echo ""
echo "Hardware Information"
echo "--------------------"
echo "CPU: $hw_cpu_model"
echo "Speed: $hw_cpu_speed MHz"
echo "RAM: $hw_ram"
echo "$hw_disk_usage"
echo "Video: $hw_video_card"
echo ""
echo "Network Information"
echo "-------------------"
echo "FQDN: $net_fqdn"
echo "Host Address: $net_host_address"
echo "Gateway IP: $net_gateway"
echo "DNS Server: $net_dns"
echo ""
echo "Interfaces Names"
echo "$net_interfaces"
echo ""
echo "Network Card: $net_make_model"
echo "IP Address: $net_ip_cidr"
echo ""
echo "System Status"
echo "-------------"
echo "Users Logged In: ${sys_users%,}"
echo "Disk Space: $sys_disk_space"
echo "Process Count: $sys_process_count"
echo "Load Averages: $sys_load_averages"
echo "Memory Allocation:"
echo "$sys_memory_allocation"
echo "Listening Network Ports: $listening_ports"
echo "UFW Rules: $ufw_rules"
echo ""

# End of Report

